[package]
name = "onyx"
version = "0.1.0"
authors = ["Joe Sheen <joe123sheen@hotmail.com>"]
edition = "2018"

[lib]
name = "onyxlib"
path = "src/lib.rs"

[dependencies]
hex = "0.4.3"
crypto-hash = "0.3.4"
rand = "0.7.3"
ed25519-dalek = "1.0.1"